general-training:
  device: cpu # {cpu vs gpu}
  batch-size: 2
  precision: 32
  include-sub-words-info-in-mask: False
dataset:
  polarities: # Ay this moment only subset of {POS, NEG, NEU}
    - POS
    - NEG
    - NEU
model:
  learning-rate: 0.0001
  add-true-spans: True
  transformer:
    learning-rate: 0.00001
    source: microsoft/deberta-base
  weighted-loss: True
  span-creator:
    loss-weight: 1.0
  triplet-extractor:
    loss-weight: 1.0
    threshold: 0.85
encoder:
  transformer:
    source: microsoft/deberta-base
    embedding-dimension: 768