general-training:
  device: cuda # {cpu vs gpu}
  batch-size: 64
  precision: 32
  include-sub-words-info-in-mask: False
dataset:
  polarities: # Ay this moment only subset of {POS, NEG, NEU}
    - POS
    - NEG
    - NEU
model:
  learning-rate: 0.0001
  add-true-spans: True
  transformer:
    learning-rate: 0.00001
    source: microsoft/deberta-base
  span-creator:
    loss-weight: 2.0
  span-classifier:
    loss-weight: 0
  triplet-extractor:
    loss-weight: 1.5
    threshold: 0.5
encoder:
  transformer:
    source: microsoft/deberta-base
    embedding-dimension: 768