general-training:
  device: cuda # {cpu vs gpu}
  batch-size: 1
  precision: 32
  include-sub-words-info-in-mask: False
  best-epoch-objective: SpanF1 # you can choose: loss and all metrics with correct prefix
dataset:
  polarities: # Ay this moment only subset of {POS, NEG, NEU}
    - POS
    - NEG
    - NEU
model:
  learning-rate: 0.0001
  transformer:
    learning-rate: 0.00001
    source: microsoft/deberta-base
  weighted-loss: True
  span_creator:
    loss-weight: 2.0
  triplet-extractor:
    loss-weight: 3.0
encoder:
  transformer:
    source: microsoft/deberta-base
    embedding-dimension: 768